# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
    ]
